# fly.toml app configuration file for uva-portal
# See https://fly.io/docs/reference/configuration/ for details.

app = 'uva-portal'
primary_region = 'iad'

[build]

[env]
  FLASK_ENV = 'production'
  PORT = '8080'
  DATA_DIR = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/api/health'

[mounts]
  source = 'uva_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

